name: ClimatePolicy

dependencies:
        - python=3.6
        - numpy
        - pandas
        - geopandas
        - rasterio
        - xarray
        - scipy
        - netCDF4
        - scikit-learn
        - matplotlib
        - cartopy
        - seaborn
        - salib
        - tqdm
        - xlrd
